name: better_auth_client
description: "A client package for Better Auth. Allow you use Better Auth in your Dart applications"
version: 0.12.1
repository: https://github.com/phantomknight287/better_auth_client

environment:
  sdk: ^3.7.0

dependencies:
  dio: ^5.8.0+1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  test: ^1.25.15
  mockito: ^5.4.4
